[project]
name = "backend"
version = "0.1.0"
description = "Backend module for Data Room application"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.121.3",
]
